### ISSUE TITLE
How does this work with coc-format-selected

### ISSUE THREAD

**Issue by nathandrew** [yaegassy/coc-php-cs-fixer#11]
I was trying to figure out how this works with `coc-format-selected`.

In the recommended settings they have the following key mappings:

```
" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)
```

When I use that key mapping the code is formatted but I'm not sure it's using this extension.

Does `coc-format-selected` use this extension under the hood?  And if not, is there a way to tell it to?

**Comment by nathandrew** [comment]
Oh, looks like that might just be a function for https://github.com/neoclide/coc-prettier – I was thinking it was more of a native call.

**Comment by yaegassy** [comment]
Sorry for the late reply.

There is no option in the `php-cs-fixer` command itself to perform formatting by specifying a range. Therefore `coc-format-selected` is not available.
