### ISSUE TITLE
Using wrong configuration

### ISSUE THREAD

**Issue by xerenahmed** [yaegassy/coc-php-cs-fixer#12]
Simply
```
A/
 .php-cs-fixer.php
  B/
   .php-cs-fixer.php
   src/
     files..
```
go inside of B directory and run 'nvim'. After open a php file and save file (so format on save). This plugin uses configuration that inside of A directory, not B. Both are git repository.

**Comment by yaegassy** [comment]
I have tried but cannot reproduce it in my environment.

It uses the configuration file directly under the workspace folder (project root), but it may be that the workspace folder you expected is not being used.

Resolved workspace folders can be check by run `:echo WorkspaceFolders`.

**Comment by xerenahmed** [comment]
Okay there is a mistake. Actually this happen in this file tree.
```
-A/
--.git
--.php-cs-fixer.php
--B/
---.git
---.php-cs-fixer.php
----C
----files..
```

go into C directory. run `:echo WorkspaceFolders` and it says it workspace "A" directory but actually in my opinion must be B directory. B directory is a git repository too.

**Comment by yaegassy** [comment]
I see. Your example looks like a rather special project example. The behavior of the workspaceFolders (project root) in the coc.nvim body is as described in this wiki. You can also manually set the workspaceFolders you need.

- <https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders>

Alternatively, you may be able to adjust it by setting `php-cs-fixer.config` at the project level, please try it.

- <https://github.com/yaegassy/coc-php-cs-fixer#precedence-of-php-cs-fixer-and-laravelpint-configuration-files-and-options>
