### ISSUE TITLE
--standard option

### ISSUE THREAD

**Issue by fcojavierdomenech** [yaegassy/coc-php-cs-fixer#13]
Is it possible to load any phpcs.xml containing a ruleset?

**Comment by yaegassy** [comment]
`coc-php-cs-fixer` is a coc extension that integrates with the `php-cs-fixer` and `laravel/pint` tools. coc-php-cs-fixer does not support PHP_CodeSniffer (`phpcs`).

Does the option "--standard" exist in php-cs-fixer or laravel/pint? I couldn't find it.

**Comment by fcojavierdomenech** [comment]
I couldn't find it either, I likely misunderstood the tool and thought it should have the same options that phpcs.

I'll create my own rules based on the phpcs.xml file. Thanks
