### ISSUE TITLE
Error on request (format): Format provider not found for buffer: 1

### ISSUE THREAD

**Issue by soyuka** [yaegassy/coc-php-cs-fixer#2]
It looks like the configuration `  "php-cs-fixer.enableFormatProvider:": true,` has no effect and is not recognized. `:Format` doesn't work for now.

**Comment by yaegassy** [comment]
I've tried it in my environment, but I can't reproduce it. :(

It looks like there is a typo in your setting. Try setting `"php-cs-fixer.enableFormatProvider": true,` not `"php-cs-fixer.enableFormatProvider:": true,`.

**Comment by yaegassy** [comment]
Did it work when configured correctly? I think it's probably the typo, so I'll close this issue.
