### ISSUE TITLE
How to fix current file only?

### ISSUE THREAD

**Issue by chinleung** [yaegassy/coc-php-cs-fixer#5]
Hi,

I was wondering if the action `php-cs-fixer.fix` only fixing the current file or the whole directory? I have it configured to fix automatically upon saving a file, and sometimes I see weird behaviour of my file getting updated as I type, so I have a feeling that it is fixing the whole directory.

If so, is there a way to only fix current buffer/file?

I'm using this to apply the fixes automatically:

```vim
autocmd BufWritePost *.php silent! CocCommand php-cs-fixer.fix
```

**Comment by yaegassy** [comment]
Hi, `php-cs-fixer.fix` command is executed only on the current file.

The flow of operation is as follows.

1. write the contents of the current file to a temporary file
2. Run php-cs-fixer against the temporary file
3. Overwrites the contents of the current file with the contents of the temporary file

Maybe the php-cs-fixer command results are slow if the file is large.

You can also check the actual command executed.

1. Run `:CocCommand workspace.showOutput`.
2. Choose "php-cs-fixer" or enter a number and enter.

**Comment by chinleung** [comment]
Thanks for the clarifications! I'll perform more tests to find out why it's happening. My file is not that large (±150 lines) and it doesn't always happen, only on some random occasions.
