### ISSUE TITLE
How can I make the plugin autosave the changes?

### ISSUE THREAD

**Issue by chinleung** [yaegassy/coc-php-cs-fixer#6]
I'm having an issue at the moment where the plugin fixes the file, but the fixes are not saved automatically.

I've tried to add an auto command but it's still saving before the formatting. So I have to save twice to have the formatting changes saved properly.

```vim
autocmd BufWritePre *.php silent! call CocCommand php-cs-fixer.fix
```

I've managed to make it work by adding a `sleep` but I don't think that's ideal.

```vim
function! PhpFixFile()
    CocCommand php-cs-fixer.fix
    sleep 700m
endfunction

autocmd BufWritePre *.php call PhpFixFile()
```

**Comment by yaegassy** [comment]
Try this configuration in `coc-setting.json` instead of `vimrc/init.vim`.

```jsonc
{
  "php-cs-fixer.enableFormatProvider": true,
  "intelephense.format.enable": false,
  "coc.preferences.formatOnSaveFiletypes": [
    "php",
  ]
}
```

**Comment by chinleung** [comment]
> 

Thanks! This worked. Didn't know about `coc.preferences.formatOnSaleFiletypes`.
